### ISSUE TITLE
dft working with dask but not withouth

### ISSUE THREAD

**Issue by apatlpo** [xgcm/xrft#29] opened 2018-06-20 09:58 UTC
The following works:
```
import numpy as np
import xarray as xr
import xrft

ds = xr.Dataset(coords={'time': ('time', np.arange(3000)*3600.), 'depth': ('depth', np.arange(10))})
ds = ds.assign(u=np.cos(2.*np.pi*2/86400.*ds.time)+0.*ds.depth)

ds = ds.chunk({'depth': 1})
u_fft = xrft.dft(ds.u.fillna(0.), dim=['time'], shift=False, detrend='linear', window=True)
print(u_fft.values)
```
But turning off chunking does not work:
```
import numpy as np
import xarray as xr
import xrft

ds = xr.Dataset(coords={'time': ('time', np.arange(3000)*3600.), 'depth': ('depth', np.arange(10))})
ds = ds.assign(u=np.cos(2.*np.pi*2/86400.*ds.time)+0.*ds.depth)

#ds = ds.chunk({'depth': 1})
u_fft = xrft.dft(ds.u.fillna(0.), dim=['time'], shift=False, detrend='linear', window=True)
print(u_fft.values)
```
And leads to:
```
(equinox) r2i2n0 datahome/aponte% python test_rft.py
Traceback (most recent call last):
  File "test_rft.py", line 9, in <module>
    u_fft = xrft.dft(ds.u.fillna(0.), dim=['time'], shift=False, detrend='linear', window=True)
  File "/home1/datahome/aponte/xrft/xrft/xrft.py", line 238, in dft
    da = _apply_detrend(da, axis_num)
  File "/home1/datahome/aponte/xrft/xrft/xrft.py", line 156, in _apply_detrend
    da = detrendn(da, axes=axis_num)
  File "/home1/datahome/aponte/xrft/xrft/xrft.py", line 100, in detrendn
    raise NotImplementedError("Detrending over more than 4 axes is "
NotImplementedError: Detrending over more than 4 axes is not implemented.
```

This looks like a bug but I could not decipher xrft enough in order to fix it.

**Comment by roxyboy** [comment] 2018-08-25 16:49
In order to parallelize the calculation, we require the axes other than being FFT'd to be chunked. Is there a reason why you don't want to chunk the `depth` dimension?

**Comment by rabernat** [comment] 2019-04-03 15:48
I believe that xrft should **always work** with numpy arrays. Users should never be required to supply dask data. So I consider this a bug that needs to be fixed.

**Comment by roxyboy** [comment] 2019-04-03 15:50
I'll try reproducing the error and see what's going wrong.

**Comment by roxyboy** [comment] 2019-04-03 18:18
I'm unable to reproduce this error...

```
ds = xr.Dataset(coords={'time': ('time', np.arange(3000)*3600.), 'depth': ('depth', np.arange(10))})
ds = ds.assign(u=np.cos(2.*np.pi*2/86400.*ds.time)+0.*ds.depth)

u_fft = xrft.dft(ds.u.fillna(0.), dim=['time'], shift=False, detrend='linear', window=True)
print(u_fft.values)
```
gives the following:
```
[[  7.64220840e-06+0.j           7.64220840e-06+0.j           7.64220840e-06+0.j
  ...,   7.64220840e-06+0.j           7.64220840e-06+0.j
    7.64220840e-06+0.j        ]
 [ -3.67124872e-04+0.35787643j  -3.67124872e-04+0.35787643j
   -3.67124872e-04+0.35787643j ...,  -3.67124872e-04+0.35787643j
   -3.67124872e-04+0.35787643j  -3.67124872e-04+0.35787643j]
 [  1.74606511e-04-0.07971875j   1.74606511e-04-0.07971875j
    1.74606511e-04-0.07971875j ...,   1.74606511e-04-0.07971875j
    1.74606511e-04-0.07971875j   1.74606511e-04-0.07971875j]
 ..., 
 [  7.02390797e-05+0.01992406j   7.02390797e-05+0.01992406j
    7.02390797e-05+0.01992406j ...,   7.02390797e-05+0.01992406j
    7.02390797e-05+0.01992406j   7.02390797e-05+0.01992406j]
 [  1.74606511e-04+0.07971875j   1.74606511e-04+0.07971875j
    1.74606511e-04+0.07971875j ...,   1.74606511e-04+0.07971875j
    1.74606511e-04+0.07971875j   1.74606511e-04+0.07971875j]
 [ -3.67124872e-04-0.35787643j  -3.67124872e-04-0.35787643j
   -3.67124872e-04-0.35787643j ...,  -3.67124872e-04-0.35787643j
   -3.67124872e-04-0.35787643j  -3.67124872e-04-0.35787643j]]
```

**Comment by roxyboy** [comment] 2019-04-05 14:52
I'm going to close this bug since the current version of `xrft` doesn't seem to produce this error.

**Comment by rabernat** [comment] 2019-04-05 14:55
It's great when bugs fix themselves! 😄

**Closed by rabernat** 2019-04-05 14:55 UTC
Labels: bug
